version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - webnet

  clona-app:
    build: .
    container_name: clona-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clona.rule=Host(`reangue.com`)"
      - "traefik.http.routers.clona.entrypoints=web"
      - "traefik.http.services.clona.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.clona-strip.stripprefix.prefixes=/clona"
      - "traefik.http.routers.clona.middlewares=clona-strip@docker"
    environment:
      - NICEGUI_HOST=0.0.0.0
      - NICEGUI_PORT=8080
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./datasets:/app/datasets
    restart: unless-stopped
    networks:
      - webnet
    ports:
      - "8080:8080"

networks:
  webnet:
    driver: bridge 