services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  clona-app:
    build: .
    container_name: clona-app
    labels:
      - "traefik.http.routers.clona.rule=Host(`reangue.com`) && PathPrefix(`/clona`)"
      - "traefik.http.routers.clona.entrypoints=web"
      - "traefik.http.services.clona.loadbalancer.server.port=8080"
    ports:
      - "80:8080"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./datasets:/app/datasets
    restart: unless-stopped 